[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.19"
solc = "./soljson-v0.8.19+commit.7dd6d404"
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]
[profile.ci]
verbosity = 4